name: deep_pick
description: A library to access deep nested values inside of dart data structures, like returned from `dynamic jsonDecode(String source)`.
version: 0.6.0
homepage: https://github.com/passsy/deep_pick

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  lint: ^1.0.0
  test: ^1.6.0
