name: deep_pick
description: Simplifies manual JSON parsing with a type-safe API. No dynamic, no manual casting. Flexible inputs types, fixed output types. Useful parsing error messages
version: 0.6.0
homepage: https://github.com/passsy/deep_pick

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  lint: ^1.0.0
  test: ^1.6.0
